// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQsrPQVAUnYFRYLOvzB1lseZx9wIJz2H8',
    appId: '1:573607173470:web:0c345e767029af82ed03cf',
    messagingSenderId: '573607173470',
    projectId: 'fir-3cb50',
    authDomain: 'fir-3cb50.firebaseapp.com',
    databaseURL: 'https://fir-3cb50-default-rtdb.firebaseio.com',
    storageBucket: 'fir-3cb50.appspot.com',
    measurementId: 'G-85T2TXV5E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFRoAXZajzby309eAQywz0JXDgvFvpSZs',
    appId: '1:573607173470:android:33549a4135b9f3abed03cf',
    messagingSenderId: '573607173470',
    projectId: 'fir-3cb50',
    databaseURL: 'https://fir-3cb50-default-rtdb.firebaseio.com',
    storageBucket: 'fir-3cb50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlVsoe-a50x0VJiJQrckNyhsF5Xo8aL78',
    appId: '1:573607173470:ios:60d254b94fdcce00ed03cf',
    messagingSenderId: '573607173470',
    projectId: 'fir-3cb50',
    databaseURL: 'https://fir-3cb50-default-rtdb.firebaseio.com',
    storageBucket: 'fir-3cb50.appspot.com',
    iosClientId: '573607173470-tt1f9riqbgnej2n7s8oa058q7uufcif9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlVsoe-a50x0VJiJQrckNyhsF5Xo8aL78',
    appId: '1:573607173470:ios:60d254b94fdcce00ed03cf',
    messagingSenderId: '573607173470',
    projectId: 'fir-3cb50',
    databaseURL: 'https://fir-3cb50-default-rtdb.firebaseio.com',
    storageBucket: 'fir-3cb50.appspot.com',
    iosClientId: '573607173470-tt1f9riqbgnej2n7s8oa058q7uufcif9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQsrPQVAUnYFRYLOvzB1lseZx9wIJz2H8',
    appId: '1:573607173470:web:c5801c4f74743155ed03cf',
    messagingSenderId: '573607173470',
    projectId: 'fir-3cb50',
    authDomain: 'fir-3cb50.firebaseapp.com',
    databaseURL: 'https://fir-3cb50-default-rtdb.firebaseio.com',
    storageBucket: 'fir-3cb50.appspot.com',
    measurementId: 'G-T4VCL59HR4',
  );
}
